name: Test

on: 
  pull_request:
    branches:
      - master

jobs:

  build:
    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017
          
    runs-on: ubuntu-latest
 
    steps:
    - name: Start MongoDB

    - uses: actions/checkout@v2
    - name: Setup node 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run dev
    - run: npm run cy:run   
      env: 
         CI: true
