name: Test

on: 
 push:
    branches: [ master ]

jobs:

  build:
    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017
          
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node 12
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Start API
      run: npm run dev & npm run cy:run
      env:
        CI: true